- build: examples/1_WakeOnMove
  photon: [0.6.3, 0.7.0, 0.8.0-rc.8]
  p1: [latest]
  electron: [0.6.4, 0.7.0, 0.8.0-rc.8]
- build: examples/2_Samples
  photon: [latest]
- build: examples/3_I2C
  electron: [latest]
- build: examples/4_Position
  photon: [latest]
- build: examples/5_Movement
  photon: [latest]
